POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "Azerty261"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "elisa@gmail.com",
    "password": "Licorne26"
}

###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTEyYTQ1YjhiYzdjZDU2MmNhNWFlZGUiLCJpYXQiOjE2Mjg2MjQ3MjIsImV4cCI6MTYyODcxMTEyMn0.ZHHZ0alknZ8ksE9GHyxsSFWTApl2wiFZ2qZMsH4MjEA

###
PUT http://localhost:3000/api/sauces/6112a4b68bc7cd562ca5aee4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTEyYTQ1YjhiYzdjZDU2MmNhNWFlZGUiLCJpYXQiOjE2Mjg2MjQ3MjIsImV4cCI6MTYyODcxMTEyMn0.ZHHZ0alknZ8ksE9GHyxsSFWTApl2wiFZ2qZMsH4MjEA
Content-Type: application/json

{
    "name": "Sauce aux oignons"
}

###

POST http://localhost:3000/api/sauces/6112a4b68bc7cd562ca5aee4/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTEyYTQ1YjhiYzdjZDU2MmNhNWFlZGUiLCJpYXQiOjE2Mjg2MjQ3MjIsImV4cCI6MTYyODcxMTEyMn0.ZHHZ0alknZ8ksE9GHyxsSFWTApl2wiFZ2qZMsH4MjEA
Content-Type: application/json

{
"like":1,
 "userId": "6112a45b8bc7cd562ca5aede"
}

###

POST http://localhost:3000/api/sauces/6112a4b68bc7cd562ca5aee4/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTEyYTQ1YjhiYzdjZDU2MmNhNWFlZGUiLCJpYXQiOjE2Mjg2MjQ3MjIsImV4cCI6MTYyODcxMTEyMn0.ZHHZ0alknZ8ksE9GHyxsSFWTApl2wiFZ2qZMsH4MjEA
Content-Type: application/json

{
"like":1,
 "userId": "6112a45b8bc7cd562ca5aede"
}